site_name: IntelOwl Documentation
site_description: "A documentation for IntelOwl."
site_author: "Matteo Lodi"

copyright: |
  &copy; Matteo Lodi

repo_name: intelowlproject/IntelOwl
repo_url: https://github.com/intelowlproject/IntelOwl

nav:
  - IntelOwl:
      - Home: "index.md"
      - Introduction: "introduction.md"
      - Installation: "installation.md"
      - Advanced Configuration: "advanced_configuration.md"
      - Usage: "usage.md"
      - Advanced Usage: "advanced_usage.md"
      - Contribute: "contribute.md"
      - API docs: "api_docs.md"

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - monorepo
  - mkdocstrings
  - swagger-ui-tag:
      background: white
      docExpansion: none
      filter: true
      syntaxHighlightTheme: monokai
      # tryItOutEnabled: true

theme:
  name: material
  # custom_dir: overrides
  logo: static/intel_owl_negative.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
  palette:
    scheme: filigran
  font:
    text: IBM Plex Sans
    code: Roboto Mono
# CSS
extra_css:
  - assets/css/custom.css
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: false
      auto_title: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      url_download: true
